// Well templates for spin drills. A template is a small patch of board around the slot, written as rows
// from top to bottom. The generator places it on the board, fills the rest with gray stack and checks it.
//   .  must be empty           *  the goal piece        #  gray stack
//   1 2 3  setup pieces in placement order (piece type comes from the shape)
//   I J L O S T Z  colored stack cells
// Fields: piece, spin ('full' | 'mini' | 'any'), lines, rows, clear (patch rows the goal clears),
// wall ('L' / 'R' when the patch must touch that wall), mirror (the mirrored well works too: S <-> Z,
// L <-> J), name (optional), id.
// With setup N, the last N numbered pieces go in the queue; earlier ones are already on the board (colored).
// The library lives in js/wells-data.js, generated by tools/mine-wells.js.
TW.module(function (TW) {
  'use strict';

  const { W, H } = TW.Board;
  const { SHAPES, TYPES, TYPE_ID, STACK_ID, cellsOf } = TW.Pieces;
  const MIRROR = { S: 'Z', Z: 'S', L: 'J', J: 'L' };

  const rand = (n) => Math.floor(Math.random() * n);
  const randInt = (a, b) => a + rand(b - a + 1);
  const cellKey = (cells) => cells.map((c) => c.join(',')).sort().join(';');

  // Finds the piece placement ({ type, rot, x, y }) that covers exactly these 4 cells, or null.
  function shapeOf(cells, onlyType) {
    if (cells.length !== 4) return null;
    const minx = Math.min(...cells.map((c) => c[0])), miny = Math.min(...cells.map((c) => c[1]));
    const want = cellKey(cells);
    for (const type of onlyType ? [onlyType] : TYPES) {
      for (let rot = 0; rot < 4; rot++) {
        const sh = SHAPES[type][rot];
        const p = { type, rot, x: minx - Math.min(...sh.map((c) => c[0])), y: miny - Math.min(...sh.map((c) => c[1])) };
        if (cellKey(cellsOf(p)) === want) return p;
      }
    }
    return null;
  }

  function mirror(t) {
    const swap = (ch) => MIRROR[ch] || ch;
    return Object.assign({}, t, {
      id: t.id + 'm',
      piece: swap(t.piece),
      rows: t.rows.map((r) => r.split('').reverse().map(swap).join('')),
      wall: t.wall === 'L' ? 'R' : t.wall === 'R' ? 'L' : t.wall,
    });
  }

  // Template text -> cells relative to the patch (x right, y down from its top row). Null if malformed.
  function parse(t) {
    const h = t.rows.length, w = t.rows[0].length;
    const out = { ...t, w, h, fixed: [], goal: [], groups: {} };
    for (let y = 0; y < h; y++) {
      if (t.rows[y].length !== w) return null;
      for (let x = 0; x < w; x++) {
        const ch = t.rows[y][x];
        if (ch === '*') out.goal.push([x, y]);
        else if (ch >= '1' && ch <= '9') (out.groups[ch] = out.groups[ch] || []).push([x, y]);
        else if (ch === '#') out.fixed.push([x, y, STACK_ID]);
        else if (TYPE_ID[ch]) out.fixed.push([x, y, TYPE_ID[ch]]);
      }
    }
    out.setups = Object.keys(out.groups).sort().map((k) => {
      const p = shapeOf(out.groups[k]);
      return p && { type: p.type, cells: out.groups[k] };
    });
    if (out.setups.some((s) => !s) || !shapeOf(out.goal, t.piece)) return null;
    out.setupMax = out.setups.length;
    return out;
  }

  let parsed = null;
  function all() {
    if (!parsed) {
      parsed = [];
      for (const t of TW.WELL_DATA || []) {
        for (const v of t.mirror ? [t, mirror(t)] : [t]) {
          const p = parse(v);
          if (p) parsed.push(p);
        }
      }
    }
    return parsed;
  }

  // Templates for this goal that have at least setupN setup pieces.
  function pool(goal, setupN) {
    return all().filter((t) => t.piece === goal.piece && t.spin === goal.spin && t.lines === goal.lines && t.setupMax >= setupN);
  }

  // Places a template on an empty board with gray stack around it. Returns
  // { board, setups: [{ type, cells }], target } in board coordinates, or null when this layout doesn't work.
  function embed(t, setupN) {
    if (t.w > W) return null;
    const g = [0, 0, 1, 1, 2][rand(5)];
    const base = H - 1 - g;
    const top = base - t.h + 1;
    const x0 = t.wall === 'L' ? 0 : t.wall === 'R' ? W - t.w : randInt(0, W - t.w);
    const at = ([x, y]) => [x0 + x, top + y];
    const board = new TW.Board();

    // Patch: fixed cells, plus the setup pieces that are already placed for this setup count.
    for (const [x, y, v] of t.fixed) board.set(x0 + x, top + y, v);
    const pre = t.setups.length - setupN;
    t.setups.slice(0, pre).forEach((s) => { for (const c of s.cells) board.set(...at(c), TYPE_ID[s.type]); });
    const setups = t.setups.slice(pre).map((s) => ({ type: s.type, cells: s.cells.map(at) }));
    const goalCells = t.goal.map(at);
    const clearRows = new Set(t.clear.map((r) => top + r));
    const topClear = Math.min(...clearRows);

    // Gray filler columns outside the patch, random-walking away from the patch edge heights.
    const colTop = (x) => { for (let y = 0; y <= base; y++) if (board.get(x, y)) return y; return base + 1; };
    const heights = new Array(W).fill(null);
    const walk = (from, to, dir) => {
      let h = colTop(from - dir);
      for (let x = from; x !== to; x += dir) {
        h = Math.max(top - 1, Math.min(topClear, h + randInt(-1, 1)));
        heights[x] = h;
      }
    };
    walk(x0 - 1, -1, -1);
    walk(x0 + t.w, W, 1);
    const outside = [];
    for (let x = 0; x < W; x++) if (heights[x] !== null) outside.push(x);

    // Rows the goal must not clear need a gap outside the patch: lower a column above the cleared rows,
    // or leave a covered hole below them.
    const holes = new Set();
    const finalFull = (y) => {
      for (let x = 0; x < W; x++) {
        const inPatch = heights[x] === null;
        const filled = inPatch
          ? board.get(x, y) || setups.some((s) => s.cells.some((c) => c[0] === x && c[1] === y)) || goalCells.some((c) => c[0] === x && c[1] === y)
          : y >= heights[x] && !holes.has(y * W + x);
        if (!filled) return false;
      }
      return true;
    };
    for (let y = top; y <= base; y++) {
      const full = finalFull(y);
      if (full === clearRows.has(y)) continue;
      if (!full || !outside.length) return null; // a cleared row is not full inside the patch
      const x = outside[rand(outside.length)];
      if (y < topClear) heights[x] = y + 1;
      else holes.add(y * W + x);
    }
    for (const x of outside) for (let y = heights[x]; y <= base; y++) if (!holes.has(y * W + x)) board.set(x, y, STACK_ID);
    for (let y = top; y <= base; y++) if (finalFull(y) !== clearRows.has(y)) return null;

    // Garbage under the patch.
    let hole = rand(W);
    for (let y = base + 1; y < H; y++) {
      if (Math.random() < 0.3) hole = rand(W);
      for (let x = 0; x < W; x++) if (x !== hole) board.set(x, y, STACK_ID);
    }

    if (board.fullRows().length || TW.Generator.removeFloating(board.clone())) return null;
    return { board, setups, target: shapeOf(goalCells, t.piece) };
  }

  TW.Wells = { all, pool, embed, parse, mirror, shapeOf };
});
